version: "3.1"
services:
  islasgeci:
    build:
      context: .
      dockerfile: Dockerfile
    image: islasgeci/zenodo_api:latest
    command: bash
    volumes:
      - $PWD:/workdir
    environment:
      ACCESS_TOKEN: $ACCESS_TOKEN

